config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :pages
  resources :teams
  resources :blogs
  devise_for :users
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Create route for /subdomain/ to redirect to /subdomain/blogs/:blog_id
  get '/:subdomain', to: 'blogs#show', id: 1, as: 'subdomain'

  # Create route for /subdomain/subtopic to redirect to /subdomain/subtopic/1
  get '/:subdomain/:subtopic', to: 'pages#show', id: 1, as: 'subdomain_page'

  # Defines the root path route ("/")
  root "home#index"

end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :blog
  belongs_to :page
  has_rich_text :content
  has_one_attached :image
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @blogs = Blog.all
    @pages = Page.all
  end

  # GET /contents/1/edit
  def edit
    @blogs = Blog.all
    @pages = Page.where(blog_id: content_params)
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:content, :blog_id, :page_id)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Content:</strong>
    <%= content.content %>
  </p>

  <p>
    <strong>Blog:</strong>
    <%= content.blog_id %>
  </p>

  <p>
    <strong>Page:</strong>
    <%= content.page_id %>
  </p>

</div>

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.label :blog_id, style: "display: block" %>
    <%= form.select :blog_id, @blogs.map { |n| [n.name, n.id] }, { :include_blank => '-- Select One --' }, :required => true %>

    <%= form.label :page_id, style: "display: block" %>
    <%= form.select :page_id, @pages.map { |n| [n.name, n.id] }, { :include_blank => '-- Select One --' }, :required => true %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contents</h1>

<div id="contents">
  <% @contents.each do |content| %>
    <%= render content %>
    <p>
      <%= link_to "Show this content", content %>
    </p>
  <% end %>
</div>

<%= link_to "New content", new_content_path %>

app/views/contents/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1>New content</h1>
    </div>
    <div class="card-body">
      <%= render "form", content: @content %>

      <br>

      <div>
        <%= link_to "Back to contents", contents_path %>
      </div>
    </div>
  </div>
</div>

app/views/contents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @content %>

<div>
  <%= link_to "Edit this content", edit_content_path(@content) %> |
  <%= link_to "Back to contents", contents_path %>

  <%= button_to "Destroy this content", @content, method: :delete %>
</div>