config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :pages
  resources :teams
  resources :blogs
  devise_for :users
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Create route for /subdomain/ to redirect to /subdomain/blogs/:blog_id
  get '/:subdomain', to: 'blogs#show', id: 1, as: 'subdomain'

  # Create route for /subdomain/subtopic to redirect to /subdomain/subtopic/1
  get '/:subdomain/:subtopic', to: 'pages#show', id: 1, as: 'subdomain_page'

  # Defines the root path route ("/")
  root "home#index"

end

app/models/blog.rb
class Blog < ApplicationRecord
  # Associations
  has_and_belongs_to_many :users, join_table: :teams, dependent: :destroy

  has_one_attached :image

  # Before save replace every space in name with a dash
  before_save :replace_spaces_with_dashes

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :subdomain, uniqueness: true


  # Replace every space in name with a dash and delete dash at the end and beginning of the string
  def replace_spaces_with_dashes
    self.subdomain = self.name.downcase.gsub(" ", "-").gsub(/^-/, "").gsub(/-$/, "")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    # Get current blog pages
    @pages = Page.where(blog_id: @blog.id)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_url, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blogs_url, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:name, :description, :subdomain, :image)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Name:</strong>
    <%= blog.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= blog.description %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= image_tag blog.image.variant(resize_to_fill: [300, 300]) if blog.image.attached? %>
  <% if blog.image.attached? %>
    <br>
  <% end %>
  
  <br>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <br>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, cols: 40, rows: 6 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1>Editing blog</h1>
    </div>
    <div class="card-body">
      <%= render "form", blog: @blog %>

      <br>

      <div class="btn-group">
        <%= button_to "View pages", @blog, method: :get, class: "btn btn-primary" %>
        <%= button_to "Back to blogs", blogs_path, method: :get, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1>Blogs</h1>
    </div>
  </div>
  <br>
</div>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <div class="col-lg-10 mx-auto">
      <div class="card shadow">
        <div class="card-header">
          <h2><%= blog.name %></h2>
        </div>
        <div class="card-body">
          <%= image_tag blog.image.variant(resize_to_fill: [300, 300]) if blog.image.attached? %>
          <% if blog.image.attached? %>
            <br>
          <% end %>
          
          <br>
          <%= blog.description%>
          <br>
          <br>
          <div class="btn-group">
            <%# /blog.subdomain/ %>
            <%= button_to "Preview as public", subdomain_path(blog.subdomain), method: :get, class: "btn btn-primary" %>
            <%= button_to "View Pages", blog_path(blog), method: :get, class: "btn btn-primary" %>
            <%= button_to "Edit this blog", edit_blog_path(blog), method: :get, class: "btn btn-primary" %>
            <%= button_to "Destroy this blog", blog, method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <br>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1>New blog</h1>
    </div>
    <div class="card-body">
      <%= render "form", blog: @blog %>

      <br>

      <div>
        <%= link_to "Back to blogs", blogs_path %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1>Pages</h1>
      <% if current_user.admin? %>
        <% if request.path == root_path || request.path.include?("pages") || request.path.include?("contents") || request.path.include?("blogs") || request.path.include?("users") %>
          <%= button_to "New page", new_page_path, method: :get, class: "btn btn-primary float-right" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
</div>

<div id="pages">
  <% @pages.each do |page| %>
    <div class="col-lg-10 mx-auto">
        <div class="card shadow">
          <div class="card-header">
            <h2><%= page.name %></h2>
          </div>
          <div class="card-body">
          <%= image_tag page.image.variant(resize_to_fill: [300, 300]) if page.image.attached? %>
          <% if page.image.attached? %>
            <br>
          <% end %>
          
          <br>
            <%= render page %>
            <div class="btn-group">
              <%# <%= button_to "Preview as public", subdomain_page_path(@blog.subdomain, page.subtopic), method: :get, class: "btn btn-primary" %> 
              <%= button_to "View Content", page_path(page), method: :get, class: "btn btn-primary" %>
              <% if request.path == root_path || request.path.include?("pages") || request.path.include?("contents") || request.path.include?("blogs") || request.path.include?("users") %>
                <%= button_to "Edit this page", edit_page_path(page), method: :get, class: "btn btn-primary" %>
                <% if current_user.admin? %>
                  <%= button_to "Destroy this page", page, method: :delete, class: "btn btn-danger" %>
                <% end %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>